language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update
  - composer install --dev -n --prefer-source
  - phpenv rehash
  - mkdir -p build/logs

script:
  - phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
